name: "Nelly"
description: "Code Habits blog"

url: "http://nellylam.github.io"
# baseurl: "http://nellylam.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments

# gems: [jekyll-font-awesome]